POST http://localhost:8181/api/doacao/fazerDoacao
Content-Type: application/json

{
  "data_doacao": "2023-11-07",
  "descricao": "Doacao de maçãs",
  "produto_doado": 2,
  "usuario_doador": 209,
  "quantidade": 10
}